# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='pytest sphinx'
        - PIP_DEPENDENCIES=''
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - EVENT_TYPE='push pull_request'

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme stsci_rtd_theme sphinx-automodapi'

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='packagename' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='packagename' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: g1u+G/i+9bqd1/Di1na55DIvs3U5rsJvvJx0PJuk3nfQU0BWyehpV0cUY+ZIJVI9yWz0pNc4SpJudwkABOPsfVmx4IGNzhdaHLsd0UI2qgz87EA+/IGOWuZ+1DnnuJ0w00V+sJEsxFXEu+LjZ0991WPl+AnMyAn8RBxrwGVTu6j7ZrTSRvlmUzIX1roSGlKVsRAtc9Rmsjra1x5/ewf+6Ilv5iZcHKJj2WxyRuinapWdZCD/gRQVELE3Kwzs+dUK9l18PeaJoD/A6M2vTKO5VrC8YlTylCpqXic6SpBnlL1LriRqX8KvfOLg54EWR03x+OAXOtkPrxpI5N6T6HvMNRVr7tvVTkxmX5dby05Fw1XH2cVbb9Vz19j8bNN3QX9ns4PnR+wvbQcIhryrJLdLgz6pk+TPDAw1VDehkD+HsheoLsqzhKsYa2qLEt4NbQterh+Zxkao1lMP6yIBp9LWZ/PT305LyA77INcghAG2AWInMeeRz5rBUwB2/KggPxnTjm6GUTL/LzbEV7xWSTw6RcDs9DHHo2YWhdfLRGJ0ZRoxt4y97lnLhqS6BzJs05CUhSqgnn7onF9y9xLS2nJdp046gsg2ROFuoJ0LfoGx9fbMYb4s5HPnonKG31YNknGSb7wQD2k9xSOyYaeoI/DYShpnA3uMruvEz/pz8zV8sSk=
  on:
    branch: master
    tags: false
